module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests'],
  testMatch: ['**/*.test.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  collectCoverageFrom: [
    'src/services/auth.service.ts',
    'src/services/admin.service.ts',
    'src/services/application.service.ts',
    'src/services/complaint.service.ts',
    'src/services/service.service.ts',
    'src/services/user.service.ts',
    'src/controllers/auth.controller.ts',
    'src/controllers/application.controller.ts',
    'src/controllers/complaint.controller.ts',
    'src/controllers/service.controller.ts',
    'src/controllers/user.controller.ts',
    'src/repositories/application.repository.ts',
    'src/repositories/complaint.repository.ts',
    'src/repositories/service.repository.ts',
    'src/repositories/user.repository.ts',
    'src/patterns/**/*.ts',
    'src/utils/apiResponse.ts',
    'src/utils/bcrypt.ts',
    'src/utils/jwt.ts',
    'src/utils/notification.util.ts',
    'src/utils/socket.ts',
    'src/validators/**/*.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 84,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  clearMocks: true,
  restoreMocks: true,
};
