import { useEffect, useState } from 'react';
import { Activity, Bell, CheckCircle, FileText, Lock, MapPin, Settings, User, Plus, Save } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/components/feedback/ToastProvider';
import api from '@/utils/api';

const tabs = [{ id: 'personal', label: 'Personal info', icon: User }, { id: 'documents', label: 'Documents', icon: FileText }, { id: 'activity', label: 'Activity', icon: Activity }, { id: 'settings', label: 'Settings', icon: Settings }];
export default function ProfilePage() {
  const { user } = useAuth(); const { addToast } = useToast(); const [tab, setTab] = useState('personal'); const [alerts, setAlerts] = useState(true); const [editing, setEditing] = useState(false); const [activities, setActivities] = useState<any[]>([]);
  useEffect(() => { if (tab !== 'activity') return; const load = () => api.get('/users/activity').then(res => setActivities(res.data.data || [])).catch(() => undefined); load(); const timer = window.setInterval(load, 10000); return () => window.clearInterval(timer); }, [tab]);
  const completion = [user?.full_name, user?.email, user?.phone, user?.district].filter(Boolean).length * 25;
  return <div className="mx-auto max-w-6xl space-y-6 text-earth-900"><section className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-emerald-700 to-green-600 p-6 text-white shadow-sm"><div className="absolute -right-10 -top-16 h-44 w-44 rounded-full bg-white/10"/><div className="relative flex flex-col justify-between gap-5 md:flex-row md:items-center"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl border-2 border-white/30 bg-emerald-100 text-xl font-bold text-emerald-700">{user?.full_name?.slice(0, 1) || 'P'}</div><div><h1 className="text-2xl font-bold">{user?.full_name || 'PolliBondhu citizen'}</h1><p className="mt-1 flex items-center gap-1 text-sm text-emerald-100"><MapPin size={14}/> {user?.district || 'Bangladesh'}</p><p className="mt-1 text-xs text-emerald-200">Verified citizen · Joined 2026</p></div></div><div className="rounded-xl border border-white/20 bg-emerald-800/30 px-5 py-3 text-center"><b className="text-xl">{completion}%</b><p className="text-xs text-emerald-100">Profile complete</p></div></div></section>
    <div className="flex flex-col gap-6 md:flex-row"><aside className="flex shrink-0 gap-1 overflow-auto rounded-2xl border border-emerald-100 bg-white p-3 shadow-sm md:block md:w-56"><div className="flex gap-1 md:block">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex min-w-max items-center gap-2 rounded-xl px-3 py-3 text-sm font-semibold md:mb-1 md:w-full ${tab === id ? 'bg-emerald-700 text-white' : 'text-earth-500 hover:bg-emerald-50'}`}><Icon size={17}/>{label}</button>)}</div></aside><main className="min-w-0 flex-1 rounded-2xl border border-emerald-100 bg-white p-6 shadow-sm">
      {tab === 'personal' && <><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Personal information</h2><button onClick={() => editing ? (setEditing(false), addToast('Profile changes saved')) : setEditing(true)} className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">{editing ? <span className="flex items-center gap-1"><Save size={14}/> Save</span> : 'Edit details'}</button></div><div className="mt-7 grid gap-x-8 gap-y-6 sm:grid-cols-2">{[['Full name', user?.full_name || '—'], ['Phone number', user?.phone || 'Add phone number'], ['Email', user?.email || '—'], ['District', user?.district || 'Add district'], ['Occupation', 'Farmer'], ['Land holding', 'Add land holding'], ['Education level', 'Add education level'], ['National ID', 'Verified']].map(([label, value]) => <label key={label} className="text-xs font-medium text-earth-500">{label}{editing && !['Email', 'National ID'].includes(label) ? <input defaultValue={value} className="mt-2 w-full rounded-lg border border-earth-200 px-3 py-2 text-sm text-earth-800"/> : <p className="mt-2 text-sm font-semibold text-earth-900">{value}{label === 'National ID' && <span className="ml-2 inline-flex items-center gap-1 rounded bg-emerald-100 px-1.5 py-0.5 text-[10px] text-emerald-700"><CheckCircle size={10}/> Verified</span>}</p>}</label>)}</div><div className="mt-8 rounded-xl border border-amber-200 bg-amber-50 p-4"><b className="text-sm">Complete your profile</b><p className="mt-1 text-xs text-earth-500">Add bank details and an emergency contact to receive faster service.</p><button onClick={() => addToast('Bank information form will be available in your next profile update.')} className="mt-3 flex items-center gap-1 rounded-lg border border-amber-300 bg-white px-3 py-2 text-xs font-bold text-amber-700"><Plus size={14}/> Add bank information</button></div></>}
      {tab === 'documents' && <><h2 className="text-lg font-bold">My documents</h2><p className="mt-1 text-sm text-earth-500">Keep these documents available for faster applications.</p><div className="mt-6 divide-y rounded-xl border border-earth-100">{[['National ID', 'Verified', '2026'], ['Birth certificate', 'Uploaded', '2026'], ['Farmer card', 'Add document', '—'], ['Land ownership record', 'Add document', '—']].map(([name, status, date]) => <div className="flex items-center justify-between p-4" key={name}><div className="flex items-center gap-3"><span className="rounded-lg bg-emerald-50 p-2 text-emerald-700"><FileText size={18}/></span><div><b className="text-sm">{name}</b><p className="text-xs text-earth-400">{status} · {date}</p></div></div><button onClick={() => addToast(`${name}: document upload is ready for backend storage integration.`)} className="text-xs font-bold text-emerald-700">{status === 'Add document' ? 'Upload' : 'View'}</button></div>)}</div></>}
      {tab === 'activity' && <><h2 className="text-lg font-bold">Activity history</h2><div className="mt-6 space-y-4 border-l border-emerald-200 pl-5">{activities.length === 0 ? <p className="text-sm text-earth-400">No activity history yet.</p> : activities.map((activity: any) => <div className="relative" key={activity.activity_id}><i className="absolute -left-[29px] top-1 h-3 w-3 rounded-full bg-emerald-500"/><b className="text-sm">{activity.action}</b><p className="mt-1 text-xs text-earth-400">{new Date(activity.created_at).toLocaleString()}</p></div>)}</div></>}
      {tab === 'settings' && <><h2 className="text-lg font-bold">Settings</h2><div className="mt-6 space-y-4"><label className="flex items-center justify-between rounded-xl border border-earth-100 p-4"><span><b className="text-sm">Notifications</b><p className="mt-1 text-xs text-earth-400">Weather, application and community updates</p></span><input type="checkbox" checked={alerts} onChange={e => { setAlerts(e.target.checked); addToast(e.target.checked ? 'Notifications enabled' : 'Notifications disabled'); }} className="h-5 w-5 accent-emerald-600"/></label><button onClick={() => addToast('Password reset support will contact you by email.')} className="flex w-full items-center gap-3 rounded-xl border border-earth-100 p-4 text-left"><Lock size={18} className="text-violet-600"/><span><b className="text-sm">Security</b><p className="mt-1 text-xs text-earth-400">Request a password reset</p></span></button></div></>}
    </main></div></div>;
}
